name: Playwright Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

jobs:
  playwright-tests:
    timeout-minutes: 90
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1,2,3]
        shardTotal: [3]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        working-directory: cypress

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: cypress

      - name: Run Playwright shard
        run: npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }} --reporter=dot,html
        env:
          CI: true
        working-directory: cypress

      - name: Upload shard report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-shard-${{ matrix.shardIndex }}
          path: playwright-report
          retention-days: 14

  merge-reports:
    if: always()
    needs: [playwright-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        working-directory: e2e

      - name: Download all shard reports
        uses: actions/download-artifact@v4
        with:
          path: all-shard-reports
          pattern: playwright-report-shard-*
          merge-multiple: true

      - name: Merge into HTML Report
        run: npx playwright show-report --output playwright-report ./all-shard-reports
        working-directory: cypress

      - name: Upload merged HTML report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report
          retention-days: 14

      - name: Upload merged report to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: playwright-report
